### ISSUE TITLE
No such method on JXBrowser when I try to login on Desktop

### ISSUE THREAD

**Issue by nrallakis** [TomGrill/gdx-facebook#19]
When I try to login on Facebook on desktop I get this error:
`Exception in Application start method
Exception in thread "Thread-2" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:403)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: javafx.stage.Stage.setAlwaysOnTop(Z)V
	at de.tomgrill.gdxfacebook.desktop.JXBrowser.start(JXBrowser.java:97)
	at com.sun.javafx.application.LauncherImpl$5.run(LauncherImpl.java:319)
	at com.sun.javafx.application.PlatformImpl$5.run(PlatformImpl.java:219)
	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:182)
	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:179)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$4.run(PlatformImpl.java:179)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:76)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication$3$1.run(GtkApplication.java:89)
	... 1 more`

**Comment by TomGrill** [comment]
JXBrowser comes with Oracle Java. OpenJDK/OpenJava does not deliver JXBrowser. Replace your current Java version with the latest from https://www.java.com/

**Comment by TomGrill** [comment]
UPDATE: I got a similar problem when starting the sample app with intellij launcher. Running with gradlew desktop:run from commandline works fine. Not sure if problems are connected to each other.

**Comment by nrallakis** [comment]
I didn't have openjdk but running from command line works fine. Thanks
