### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/application/Application problem

### ISSUE THREAD

**Issue by Aperico-com** [TomGrill/gdx-facebook#40]
I get this error trying to use the signin feature from desktop. I have already done the GDXFacebookSystem.install(config); and checking with isLoaded();

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: javafx/application/Application
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.tomgrill.gdxfacebook.desktop.DesktopGDXFacebook.startGUISignIn(DesktopGDXFacebook.java:66)
	at de.tomgrill.gdxfacebook.desktop.DesktopGDXFacebook.signIn(DesktopGDXFacebook.java:48)
	at com.aperico.game.sylvass.view.LoginWindow.loginFBWithReadPermissions(LoginWindow.java:113)
	at com.aperico.game.sylvass.view.LoginWindow.access$6(LoginWindow.java:106)
	at com.aperico.game.sylvass.view.LoginWindow$5.changed(LoginWindow.java:360)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

```

I tried running it from command prompt with gradlew desktop:run but same thing. I got no complaints in eclipse and I can see that the desktop project got the gradle dependencies facebook-core and facebook-desktop jars.

I can even open up the de.tomgrill.gdxfacebook.desktop.DesktopDGXFacebook.class and de.tomgrill.gdxfacebook.desktop.JXBrowser.class files in eclipse so they are there...

Tried ofc clean/re-build in eclipse and from gradlew cmd prompt. I use oracle 1.7.0_25 and tried to use both 1.6 and 1.7 code compilance. Got any ideas?

**Comment by Zomis** [comment]
I would recommend using Java 8 for this. Starting with Java 8, JavaFX is distributed as a part of the JRE, earlier it was more complicated to use JavaFX. I am using Java 8 and it works perfectly fine for me.

**Comment by TomGrill** [comment]
... and verify that you run Oracle JAVA no other variant.

**Comment by Aperico-com** [comment]
" I use oracle 1.7.0_25" so yes that is verified. I did also try using Java 8u112 and it then worked. This creates a new problem since I also use Packr and Java 1.7 for that.

I am currently using gdx-facebook 1.25-snapshot, would rolling back to an earlier version say 1.24 make it work with Java 1.7?

My guess is no and I only need the login functionality so I will probably make my own implementation if this won't work, thanks you

**Comment by TomGrill** [comment]
Earlier version will not work. javafx.* package is required since the extension was released.

**Comment by Aperico-com** [comment]
Yeah, I just noticed that, thanks for the help. Closing.

**Comment by asisadh** [comment]
Is this issue solved ? As I m using Android Studio for development and it is using openJDK. And i m getting same error as mention above and could not found any help to resolve my issue. I was unable to change open jdk to oracle jdk. The project run fine on android but same expection on the Desktop. I knw i m missing jfk jar but could not understand how to add on my project.

**Comment by TomGrill** [comment]
You need oracle JDK, no way around that I know of.
