### ISSUE TITLE
ld: framework not found FBSDKShareKit

### ISSUE THREAD

**Issue by MrCharli3** [TomGrill/gdx-facebook#49]
Hi, any idea why I'm getting this error now? Has worked fine before. Anything you've run into before?

```
[ERROR] ld: framework not found FBSDKShareKit
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o "/Users/space/party_game/ios/robovm-build/tmp/Unnamed/ios/thumbv7/Space Pack" -arch armv7 -Wl,-filelist,/Users/space/party_game/ios/robovm-build/tmp/Unnamed/ios/thumbv7/objects0 -L /Users/space/.robovm-sdks/robovm-2.3.0/lib/vm/ios/thumbv7 -ObjC -Xlinker -alias_list -Xlinker /Users/space/party_game/ios/robovm-build/tmp/Unnamed/ios/thumbv7/aliased_symbols -exported_symbols_list /Users/space/party_game/ios/robovm-build/tmp/Unnamed/ios/thumbv7/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/space/party_game/ios/libs -fPIC -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -lrobovm-bc -force_load /Users/space/.robovm-sdks/robovm-2.3.0/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework GoogleMobileAds -framework AdSupport -framework AudioToolbox -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreMotion -framework CoreTelephony -framework CoreVideo -framework GLKit -framework MediaPlayer -framework MessageUI -framework OpenGLES -framework QuartzCore -framework SafariServices -framework StoreKit -framework SystemConfiguration -framework FBSDKShareKit -framework Bolts -framework FBSDKCoreKit -framework FBNotifications -framework ImageIO -framework UIKit -framework FBSDKLoginKit -framework FBSDKMessengerShareKit -framework OpenAL -force_load /Users/space/.robovm/cache/ios/thumbv7/release/Users/space/.gradle/caches/modules-2/files-2.1/com.mobidevelop.robovm/robopods-google-mobile-ads-ios/2.2.1/70c62b831c469d6517738b55a357ec66f1461720/robopods-google-mobile-ads-ios-2.2.1.jar.extracted/META-INF/robovm/ios/libs/libGGLAdMob.a -lz -force_load /Users/space/.robovm/cache/ios/thumbv7/release/Users/space/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.9.5/2349dc0e71f911f0eff53c8e0cf3573701d62249/gdx-freetype-platform-1.9.5-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx-freetype.a -force_load /Users/space/.robovm/cache/ios/thumbv7/release/Users/space/.gradle/caches/modules-2/files-2.1/com.mobidevelop.robovm/robopods-google-apis-ios/2.2.1/200fc3ce120ac2a34d88fadf3e725cb15cacabc2/robopods-google-apis-ios-2.2.1.jar.extracted/META-INF/robovm/ios/libs/libGGLCore.a -force_load /Users/space/.robovm/cache/ios/thumbv7/release/Users/space/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.5/80fed8c3dbf915df8e93c0ed8943e2e5e569e513/gdx-platform-1.9.5-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/space/.robovm/cache/ios/thumbv7/release/Users/space/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.5/80fed8c3dbf915df8e93c0ed8943e2e5e569e513/gdx-platform-1.9.5-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:269)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:327)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:263)
	at org.robovm.compiler.Linker.link(Linker.java:421)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:467)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:776)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
```

**Comment by MrCharli3** [comment]
This was fixed by adding the .framework to libs folder. However, I have never needed to manually add the Frameworks before, any idea why I needed to now?

**Comment by TomGrill** [comment]
This is mentioned in the wiki: https://github.com/TomGrill/gdx-facebook/wiki/3.-Setup-gdx-facebook

The reason is that latest facebook robopods no longer bring the framework lib with them. https://github.com/MobiDevelop/robovm-robopods/tree/master/facebook
