### ISSUE TITLE
Terminating app due to uncaught exception 'java.lang.UnsatisfiedLinkError'

### ISSUE THREAD

**Issue by rohitgoyal** [TomGrill/gdx-facebook#53]
I have integrated gdx-facebook in my libgdx project. 
It is working fine in my android app but on iOS the app is crashing on start up with below exception.
```

2017-11-12 12:39:47.837453+0530 MY_APP[3408:173492] *** Terminating app due to uncaught exception 'java.lang.UnsatisfiedLinkError', reason: 'java.lang.UnsatisfiedLinkError: No implementation found for void com.badlogic.gdx.backends.iosrobovm.IOSGLES20.init() (tried Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_init and Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_init__)
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES20.init(Native Method)
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES20.<init>(IOSGLES20.java:28)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.init(IOSGraphics.java:125)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.init(IOSGraphics.java:195)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication.createGraphics(IOSApplication.java:193)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication.init(IOSApplication.java:176)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication.didFinishLaunching(IOSApplication.java:134)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication$Delegate.applicationDidFinishLaunchingWithOptions(IOSApplication.java:75)
	at com.paxplay.MY_APP.IOSMoeLauncher.applicationDidFinishLaunchingWithOptions(IOSMoeLauncher.java:49)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at com.paxplay.MY_APP.IOSMoeLauncher.main(IOSMoeLauncher.java:31)
'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000001789e1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000017200f41 objc_exception_throw + 48
	2   MOE                                 0x0000000012c51f05 _Z29hasObjCRuntimeBeenInitializedv + 0
	3   MOE                                 0x0000000012c5772a _Z26nativeToJavaMessageHandlerP7ffi_cifPvPS1_S1_ + 1519
	4   MOE                                 0x0000000012c5e629 ffi_closure_unix64_inner + 487
	5   MOE                                 0x0000000012c5dbb2 ffi_closure_unix64 + 72
	6   UIKit                               0x0000000014a91db7 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4105
	7   UIKit                               0x0000000014a97245 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1720
	8   UIKit                               0x0000000014e52c6c __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 924
	9   UIKit                               0x00000000152203ef +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	10  UIKit                               0x0000000014e52865 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 249
	11  UIKit                               0x0000000014e530c3 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 668
	12  UIKit                               0x00000000157b0c11 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 262
	13  UIKit                               0x00000000157b0aca -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 444
	14  UIKit                               0x000000001549eb9c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 420
	15  UIKit                               0x0000000015699c3e _performActionsWithDelayForTransitionContext + 100
	16  UIKit                               0x000000001549e998 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 231
	17  UIKit                               0x000000001521fa4c -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	18  UIKit                               0x0000000014a95ac6 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 523
	19  UIKit                               0x000000001505e523 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 369
	20  FrontBoardServices                  0x000000001ae78158 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 338
	21  FrontBoardServices                  0x000000001ae80c4d __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 235
	22  libdispatch.dylib                   0x0000000018f6b43c _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x0000000018f70af4 _dispatch_block_invoke_direct + 592
	24  FrontBoardServices                  0x000000001aeac672 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	25  FrontBoardServices                  0x000000001aeac328 -[FBSSerialQueue _performNext] + 464
	26  FrontBoardServices                  0x000000001aeac897 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	27  CoreFoundation                      0x00000000178412b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	28  CoreFoundation                      0x00000000178e0d31 __CFRunLoopDoSource0 + 81
	29  CoreFoundation                      0x0000000017825c19 __CFRunLoopDoSources0 + 185
	30  CoreFoundation                      0x00000000178251ff __CFRunLoopRun + 1279
	31  CoreFoundation                      0x0000000017824a89 CFRunLoopRunSpecific + 409
	32  GraphicsServices                    0x000000001b7859c6 GSEventRunModal + 62
	33  UIKit                               0x0000000014a98d30 UIApplicationMain + 159
	34  MOE                                 0x0000000012c5da0d ffi_call_unix64 + 85
	35  ???                                 0x00007fff537b3650 0x0 + 140734593971792
)
libc++abi.dylib: terminating with uncaught exception of type ObjCException

```

**Comment by TomGrill** [comment]
I do not see the relation to the gdx-facebook extension. Looks to me more of an libgdx issue. 
Please try the example app: https://github.com/TomGrill/gdx-facebook-app and let me know if that error shows again.

Did you think of updating proguard rules accordingly?

**Comment by rohitgoyal** [comment]
It has happened after integrating gdx-facebook only.

According to logs it is crashing at 
      return super.applicationDidFinishLaunchingWithOptions(application, launchOptions);

Though as i try to build the app through Android Studio then the build is also failing with below message. 

ld: warning: directory not found for option '-F/Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/sym/Debug-iphonesimulator/Bolts'
ld: warning: directory not found for option '-F/Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/sym/Debug-iphonesimulator/FBSDKCoreKit'
ld: warning: directory not found for option '-F/Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/sym/Debug-iphonesimulator/FBSDKLoginKit'
ld: warning: directory not found for option '-F/Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/sym/Debug-iphonesimulator/FBSDKShareKit'
ld: warning: -pagezero_size not page aligned, rounding down
ld: framework not found Bolts
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/obj/ios-moe.build/Debug-iphonesimulator/ios-moe.build/Objects-normal/x86_64/JumpyTile normal x86_64
	Ld /Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/obj/ios-moe.build/Debug-iphonesimulator/ios-moe.build/Objects-normal/i386/JumpyTile normal i386
(2 failures)



 FAILED

BUILD FAILED

Total time: 7.388 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios-moe:moeMainDebugIphonesimulatorXcodeBuild'.
> Task failed, you can find the log file here: /Users/rohitgoyal/Desktop/PaxPlay/libGDXProjects/JumpyTile/ios-moe/build/moe/xcodebuild/XcodeBuild-main-debug-iphonesimulator.log

**Comment by TomGrill** [comment]
Is the example app running: https://github.com/TomGrill/gdx-facebook-app ?
