### ISSUE TITLE
[Android] java.lang.RuntimeException: GDXFacebookSystem has already been installed.

### ISSUE THREAD

**Issue by StanDem** [TomGrill/gdx-facebook#6]
09-07 06:41:12.806    2545-3491/com.sunraygames.oceanix W/dalvikvm﹕ threadid=20: thread exiting with uncaught exception (group=0xa4b7b648)
09-07 06:41:12.806    2545-3491/com.sunraygames.oceanix E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 207
    java.lang.RuntimeException: GDXFacebookSystem has already been installed. You may not call install() more than once.
            at de.tomgrill.gdxfacebook.core.GDXFacebookSystem.install(GDXFacebookSystem.java:66)
            at com.sunraygames.oceanux.Game$1.<init>(Game.java:82)
            at com.sunraygames.oceanux.Game.create(Game.java:82)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:241)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

my code (error line):
  facebook = GDXFacebookSystem.install(config);

This happens sometimes when you minimize an app and then try to return back. But between these moments the app should stay in background for a while and you can run other apps to force some memory cleaning.

**Comment by TomGrill** [comment]
Should be fixed. Refresh you gradle dependencies.

**Comment by StanDem** [comment]
Yes, it is fixed. Thank you.
